import type { EventFormValue } from '@/components/calendar/EventModal';
import type { WeekendResearch, WeekendResearchItem } from '@/hooks/useWeekendResearch';

export interface WeekendEventPick {
  id: string;
  weekendKey: string;
  weekendLabel: string;
  tabLabel: string;
  title: string;
  emoji: string;
  categoryId: string;
  dateLabel: string;
  start: string;
  end: string;
  area: string;
  locationName: string;
  nearestStation: string;
  price: string;
  reservation: string;
  rainFriendly?: boolean;
  tags: string[];
  summary: string;
  coupleNote?: string;
  sourceName: string;
  url: string;
  imageUrl?: string;
  imageQuery: string;
}

export interface WeekendEventGroup {
  key: string;
  label: string;
  tabLabel: string;
  startsOn: string;
  endsOn: string;
  events: WeekendEventPick[];
}

const makeEvent = (group: Omit<WeekendEventGroup, 'events'>, item: Omit<WeekendEventPick, 'weekendKey' | 'weekendLabel' | 'tabLabel'>): WeekendEventPick => ({
  ...item,
  weekendKey: group.key,
  weekendLabel: group.label,
  tabLabel: group.tabLabel,
});

const groups = [
  {
    key: '2026-08-22',
    label: '2026/08/22(土)-08/23(日)',
    tabLabel: '8/22-23',
    startsOn: '2026-08-22',
    endsOn: '2026-08-23',
  },
  {
    key: '2026-08-29',
    label: '2026/08/29(土)-08/30(日)',
    tabLabel: '8/29-30',
    startsOn: '2026-08-29',
    endsOn: '2026-08-30',
  },
  {
    key: '2026-09-05',
    label: '2026/09/05(土)-09/06(日)',
    tabLabel: '9/5-6',
    startsOn: '2026-09-05',
    endsOn: '2026-09-06',
  },
  {
    key: '2026-09-12',
    label: '2026/09/12(土)-09/13(日)',
    tabLabel: '9/12-13',
    startsOn: '2026-09-12',
    endsOn: '2026-09-13',
  },
  {
    key: '2026-09-19',
    label: '2026/09/19(土)-09/21(月祝)',
    tabLabel: '9/19-21',
    startsOn: '2026-09-19',
    endsOn: '2026-09-21',
  },
  {
    key: '2026-09-26',
    label: '2026/09/26(土)-09/27(日)',
    tabLabel: '9/26-27',
    startsOn: '2026-09-26',
    endsOn: '2026-09-27',
  },
  {
    key: '2026-10-03',
    label: '2026/10/03(土)-10/04(日)',
    tabLabel: '10/3-4',
    startsOn: '2026-10-03',
    endsOn: '2026-10-04',
  },
  {
    key: '2026-10-10',
    label: '2026/10/10(土)-10/12(月祝)',
    tabLabel: '10/10-12',
    startsOn: '2026-10-10',
    endsOn: '2026-10-12',
  },
  {
    key: '2026-10-17',
    label: '2026/10/17(土)-10/18(日)',
    tabLabel: '10/17-18',
    startsOn: '2026-10-17',
    endsOn: '2026-10-18',
  },
  {
    key: '2026-10-24',
    label: '2026/10/24(土)-10/25(日)',
    tabLabel: '10/24-25',
    startsOn: '2026-10-24',
    endsOn: '2026-10-25',
  },
] as const;

export const MONTHLY_WEEKEND_EVENTS: WeekendEventGroup[] = [
  {
    ...groups[0],
    events: [
      makeEvent(groups[0], {
        id: '2026-08-22-azabujuban-noryo',
        title: '第60回 麻布十番納涼まつり',
        emoji: '🏮',
        categoryId: 'date',
        dateLabel: '8/22(土)-8/23(日)',
        start: '2026-08-22T17:00:00+09:00',
        end: '2026-08-22T20:30:00+09:00',
        area: '麻布十番',
        locationName: '麻布十番商店街一帯',
        nearestStation: '麻布十番駅 徒歩2分',
        price: '入場無料。飲食・物販は有料',
        reservation: '不要。混雑と交通規制を要確認',
        rainFriendly: false,
        tags: ['無料', '夏祭り', '屋台', '夕方'],
        summary: '15時から21時まで開催される麻布十番の大型夏祭り。屋台と商店街グルメを夕方から回れる。',
        coupleNote: '混雑が強いので17時台に入り、六本木か赤羽橋方面へ抜ける帰路を先に決めると安全。',
        sourceName: '東京の観光公式サイト GO TOKYO',
        url: 'https://www.gotokyo.org/jp/spot/ev095/index.html',
        imageQuery: '麻布十番 納涼まつり 2026',
      }),
      makeEvent(groups[0], {
        id: '2026-08-22-shinagawa-hanabi-aquapark',
        title: '品川花火まつり',
        emoji: '🐬',
        categoryId: 'date',
        dateLabel: '8/22(土)-8/23(日) 夜',
        start: '2026-08-22T19:00:00+09:00',
        end: '2026-08-22T21:30:00+09:00',
        area: '品川',
        locationName: 'マクセル アクアパーク品川',
        nearestStation: '品川駅 徒歩約2分',
        price: '水族館入場料',
        reservation: '混雑日はチケット事前確認推奨',
        rainFriendly: true,
        tags: ['屋内', '水族館', '花火演出', '夜'],
        summary: '水族館の夏イベント。屋内で涼しく、夜の演出と合わせて使いやすい。',
        coupleNote: '暑さと雨を避けたい時の本命。品川駅近くで食事にもつなげやすい。',
        sourceName: 'マクセル アクアパーク品川公式',
        url: 'https://www.aqua-park.jp/aqua/shinagawahanabimatsuri2026/index.html',
        imageQuery: '品川花火まつり アクアパーク品川',
      }),
      makeEvent(groups[0], {
        id: '2026-08-23-oshima-komatsugawa-stargazing',
        title: '大島小松川公園 星空観察会',
        emoji: '🔭',
        categoryId: 'date',
        dateLabel: '8/23(日) 夜',
        start: '2026-08-23T19:00:00+09:00',
        end: '2026-08-23T21:00:00+09:00',
        area: '江東区・大島',
        locationName: '大島小松川公園',
        nearestStation: '東大島駅 徒歩約3分',
        price: '無料',
        reservation: '天候と開催可否を直前確認',
        rainFriendly: false,
        tags: ['無料', '星空', '公園', '夜'],
        summary: '都立公園で夏の星座を観察する夜イベント。都心から近く、短時間の夜デートにしやすい。',
        coupleNote: '晴れなら候補。曇りや雨なら品川、みなと科学館、プラネタリウムへ切替。',
        sourceName: '都立公園公式情報',
        url: 'https://tokyo-eastpark.com/event/%E3%80%90%E5%A4%A7%E5%B3%B6%E5%B0%8F%E6%9D%BE%E5%B7%9D%E5%85%AC%E5%9C%92%E3%80%918-23%E6%97%A5%E3%80%8E%E6%98%9F%E7%A9%BA%E8%A6%B3%E5%AF%9F%E4%BC%9A%EF%BD%9E%E5%A4%8F%E3%81%AE%E6%98%9F%E5%BA%A7',
        imageQuery: '大島小松川公園 星空観察会',
      }),
    ],
  },
  {
    ...groups[1],
    events: [
      makeEvent(groups[1], {
        id: '2026-08-29-super-yosakoi',
        title: '原宿表参道元氣祭 スーパーよさこい2026',
        emoji: '💃',
        categoryId: 'date',
        dateLabel: '8/29(土)-8/30(日)',
        start: '2026-08-29T10:00:00+09:00',
        end: '2026-08-29T19:30:00+09:00',
        area: '原宿・表参道',
        locationName: '代々木公園イベント広場・表参道周辺',
        nearestStation: '原宿駅・明治神宮前駅',
        price: '観覧無料',
        reservation: '不要。混雑と交通規制を確認',
        rainFriendly: false,
        tags: ['無料', '祭り', '踊り', '原宿'],
        summary: '原宿、表参道、代々木公園で開催される大規模よさこいイベント。夏の終わりに熱量が高い。',
        coupleNote: '原宿から表参道カフェへ逃げやすい。短時間だけ見て食事に移るのが現実的。',
        sourceName: '東京都公園協会 代々木公園イベント情報',
        url: 'https://www.tokyo-park.or.jp/park/yoyogi/news/2026/8.html',
        imageQuery: 'スーパーよさこい 原宿 表参道',
      }),
      makeEvent(groups[1], {
        id: '2026-08-29-sarue-nature',
        title: '猿江恩賜公園 生きもの観察',
        emoji: '🦋',
        categoryId: 'date',
        dateLabel: '8/29(土)-8/30(日)',
        start: '2026-08-30T10:00:00+09:00',
        end: '2026-08-30T12:00:00+09:00',
        area: '江東区・住吉',
        locationName: '猿江恩賜公園',
        nearestStation: '住吉駅 徒歩約2分',
        price: '無料または公式案内確認',
        reservation: '公式案内確認',
        rainFriendly: false,
        tags: ['公園', '自然', '昼', '低予算'],
        summary: '都立公園の生きもの観察イベント。午前に軽く外へ出るプランに向く。',
        coupleNote: '派手さは弱いが近場で軽い。暑ければ錦糸町や清澄白河の屋内へ寄せる。',
        sourceName: 'My TOKYO 東京都公式ポータル',
        url: 'https://www.my.metro.tokyo.lg.jp/event/',
        imageQuery: '猿江恩賜公園 生きもの観察',
      }),
      makeEvent(groups[1], {
        id: '2026-08-30-maeda-kanji',
        title: '生誕130年 前田寛治展',
        emoji: '🖼️',
        categoryId: 'date',
        dateLabel: '8/30(日)まで',
        start: '2026-08-30T13:00:00+09:00',
        end: '2026-08-30T15:00:00+09:00',
        area: '東京駅',
        locationName: '東京ステーションギャラリー',
        nearestStation: '東京駅直結',
        price: '一般1,600円',
        reservation: 'チケット確認',
        rainFriendly: true,
        tags: ['屋内', '展覧会', '東京駅', '雨の日'],
        summary: '洋画家・前田寛治の回顧展。東京駅直結で、暑さや雨の日にも組みやすい。',
        coupleNote: '表参道の混雑が重い時の代替。丸の内ごはんとセットにできる。',
        sourceName: '東京の観光公式サイト GO TOKYO',
        url: 'https://www.gotokyo.org/jp/see-and-do/arts-and-design/art-and-exhibitions/index.html',
        imageQuery: '前田寛治展 東京ステーションギャラリー',
      }),
    ],
  },
  {
    ...groups[2],
    events: [
      makeEvent(groups[2], {
        id: '2026-09-05-china-festival',
        title: 'チャイナフェスティバル2026',
        emoji: '🥟',
        categoryId: 'meal',
        dateLabel: '9/5(土)-9/6(日)',
        start: '2026-09-05T11:00:00+09:00',
        end: '2026-09-05T20:00:00+09:00',
        area: '代々木',
        locationName: '代々木公園イベント広場',
        nearestStation: '原宿駅・明治神宮前駅',
        price: '入場無料。飲食は有料',
        reservation: '不要',
        rainFriendly: false,
        tags: ['無料入場', 'フード', '国際交流', '屋外'],
        summary: '中華グルメ、ステージ、文化企画をまとめて楽しむ代々木公園のイベント。',
        coupleNote: '食べ歩き向け。昼の暑さが強ければ夕方から入る。',
        sourceName: '東京都公園協会 代々木公園イベント情報',
        url: 'https://www.tokyo-park.or.jp/park/yoyogi/news/2026/8.html',
        imageQuery: 'チャイナフェスティバル2026 代々木公園',
      }),
      makeEvent(groups[2], {
        id: '2026-09-06-takashima-nojuro',
        title: '没後50年 髙島野十郎展',
        emoji: '🕯️',
        categoryId: 'date',
        dateLabel: '9/6(日)まで',
        start: '2026-09-06T13:00:00+09:00',
        end: '2026-09-06T15:00:00+09:00',
        area: '渋谷・松濤',
        locationName: '渋谷区立松濤美術館',
        nearestStation: '神泉駅・渋谷駅',
        price: '観覧料確認',
        reservation: '不要または公式確認',
        rainFriendly: true,
        tags: ['屋内', '展覧会', '美術館', '渋谷'],
        summary: 'ろうそくなど静かな作品で知られる髙島野十郎の展覧会。渋谷周辺の屋内デートに向く。',
        coupleNote: '派手ではないが落ち着く。展示後に松濤、奥渋、神泉で食事へつなげやすい。',
        sourceName: '東京の観光公式サイト GO TOKYO',
        url: 'https://www.gotokyo.org/jp/see-and-do/arts-and-design/art-and-exhibitions/index.html',
        imageQuery: '髙島野十郎展 松濤美術館',
      }),
      makeEvent(groups[2], {
        id: '2026-09-06-miraikan-antarctica',
        title: '特別展「南極」',
        emoji: '🧊',
        categoryId: 'date',
        dateLabel: '9/27(日)まで',
        start: '2026-09-06T13:00:00+09:00',
        end: '2026-09-06T15:30:00+09:00',
        area: 'お台場',
        locationName: '日本科学未来館',
        nearestStation: 'テレコムセンター駅・東京国際クルーズターミナル駅',
        price: '一般2,000円',
        reservation: 'チケット確認',
        rainFriendly: true,
        tags: ['屋内', '科学館', '涼しい', 'お台場'],
        summary: '南極観測70年をテーマに、実物の南極の氷や資料を見られる特別展。',
        coupleNote: '暑い日の安定候補。お台場で夕景や食事に流せる。',
        sourceName: '東京の観光公式サイト GO TOKYO',
        url: 'https://www.gotokyo.org/en/see-and-do/arts-and-design/art-and-exhibitions/',
        imageQuery: '日本科学未来館 特別展 南極 2026',
      }),
    ],
  },
  {
    ...groups[3],
    events: [
      makeEvent(groups[3], {
        id: '2026-09-13-sumo-september',
        title: '大相撲九月場所 初日',
        emoji: '🏯',
        categoryId: 'date',
        dateLabel: '9/13(日) 初日',
        start: '2026-09-13T13:00:00+09:00',
        end: '2026-09-13T18:00:00+09:00',
        area: '両国',
        locationName: '両国国技館',
        nearestStation: '両国駅 徒歩約2分',
        price: 'チケット制',
        reservation: '前売券確認',
        rainFriendly: true,
        tags: ['屋内', '相撲', '和文化', '両国'],
        summary: '令和八年九月場所の初日。観戦と両国散歩をセットにできる。',
        coupleNote: '日本っぽい体験でレベッカにも刺さりやすい。チケット有無を先に確認。',
        sourceName: '日本相撲協会公式',
        url: 'https://www.sumo.or.jp/Watching/isolate/637/',
        imageQuery: '大相撲 九月場所 両国国技館',
      }),
      makeEvent(groups[3], {
        id: '2026-09-13-disneysea-summer',
        title: '東京ディズニーシー サマー・クールオフ',
        emoji: '🌊',
        categoryId: 'date',
        dateLabel: '9/14(月)まで',
        start: '2026-09-13T09:00:00+09:00',
        end: '2026-09-13T21:00:00+09:00',
        area: '舞浜',
        locationName: '東京ディズニーシー',
        nearestStation: '舞浜駅・東京ディズニーシー・ステーション',
        price: '1デーパスポート料金確認',
        reservation: 'チケット事前購入',
        rainFriendly: false,
        tags: ['テーマパーク', '夏イベント', '舞浜'],
        summary: '9月前半までの夏イベント最終週。1日使う本格デート候補。',
        coupleNote: 'コストは高いが満足度は高い。天気と混雑を見て早め判断。',
        sourceName: '東京ディズニーリゾート公式',
        url: 'https://www.tokyodisneyresort.jp/tds/daily/calendar/20260913/',
        imageQuery: '東京ディズニーシー サマー クールオフ 2026',
      }),
      makeEvent(groups[3], {
        id: '2026-09-13-miraikan-antarctica',
        title: '特別展「南極」',
        emoji: '🐧',
        categoryId: 'date',
        dateLabel: '開催中',
        start: '2026-09-13T13:00:00+09:00',
        end: '2026-09-13T15:30:00+09:00',
        area: 'お台場',
        locationName: '日本科学未来館',
        nearestStation: 'テレコムセンター駅・東京国際クルーズターミナル駅',
        price: '一般2,000円',
        reservation: 'チケット確認',
        rainFriendly: true,
        tags: ['屋内', '科学館', '雨の日', 'お台場'],
        summary: '南極の氷や観測資料を見る屋内展示。暑さ、雨、台風時の代替にも使える。',
        coupleNote: '半日で組みやすく、帰りに台場の夜景へつなげられる。',
        sourceName: '東京の観光公式サイト GO TOKYO',
        url: 'https://www.gotokyo.org/en/see-and-do/arts-and-design/art-and-exhibitions/',
        imageQuery: '日本科学未来館 特別展 南極 2026',
      }),
    ],
  },
  {
    ...groups[4],
    events: [
      makeEvent(groups[4], {
        id: '2026-09-19-tokyo-game-show',
        title: '東京ゲームショウ2026',
        emoji: '🎮',
        categoryId: 'date',
        dateLabel: '9/19(土)-9/21(月祝)',
        start: '2026-09-19T09:30:00+09:00',
        end: '2026-09-19T17:00:00+09:00',
        area: '幕張',
        locationName: '幕張メッセ',
        nearestStation: '海浜幕張駅',
        price: 'チケット制',
        reservation: 'チケット事前確認',
        rainFriendly: true,
        tags: ['屋内', 'ゲーム', '大型イベント', '幕張'],
        summary: '一般公開が9月19日から21日までの大型ゲームイベント。展示、試遊、物販をまとめて回れる。',
        coupleNote: '混雑は強いが話題性は高い。ゲーム好きなら本命、そうでなければ短時間でも疲れる。',
        sourceName: '東京ゲームショウ公式',
        url: 'https://tgs.cesa.or.jp/2026/?public=true',
        imageQuery: '東京ゲームショウ2026 幕張メッセ',
      }),
      makeEvent(groups[4], {
        id: '2026-09-20-tokyo-craft-festa',
        title: '東京クラフトFESTA2026 feat. 多摩',
        emoji: '🍺',
        categoryId: 'meal',
        dateLabel: '9/20(日)-9/21(月祝)',
        start: '2026-09-20T10:00:00+09:00',
        end: '2026-09-20T20:00:00+09:00',
        area: '新宿・都庁',
        locationName: '東京都庁 都民広場',
        nearestStation: '都庁前駅・新宿駅',
        price: '入場無料想定。飲食・物販は有料',
        reservation: '不要または公式確認',
        rainFriendly: false,
        tags: ['クラフト', 'フード', '都庁', '多摩'],
        summary: '多摩地域のクラフト雑貨、ワークショップ、クラフトビール、ご当地フードを集める予定のイベント。',
        coupleNote: '新宿なのでアクセス良好。内容詳細は順次公開なので直前に再確認。',
        sourceName: '東京クラフトFESTA公式',
        url: 'https://www.craft-festa.tokyo/',
        imageQuery: '東京クラフトFESTA2026 都民広場',
      }),
      makeEvent(groups[4], {
        id: '2026-09-20-disney-halloween',
        title: '東京ディズニーシー ディズニー・ハロウィーン',
        emoji: '🎃',
        categoryId: 'date',
        dateLabel: '9/16(水)-10/31(土)',
        start: '2026-09-20T09:00:00+09:00',
        end: '2026-09-20T21:00:00+09:00',
        area: '舞浜',
        locationName: '東京ディズニーシー',
        nearestStation: '舞浜駅・東京ディズニーシー・ステーション',
        price: '1デーパスポート料金確認',
        reservation: 'チケット事前購入',
        rainFriendly: false,
        tags: ['ハロウィーン', 'テーマパーク', '舞浜'],
        summary: '9月16日からハロウィーン期間。ディズニーシー25周年企画とも重なる。',
        coupleNote: '全日使う高コスト候補。仮装可否や混雑を確認してから決める。',
        sourceName: '東京ディズニーリゾート公式',
        url: 'https://www.tokyodisneyresort.jp/tds/daily/calendar/20260920/',
        imageQuery: '東京ディズニーシー ハロウィーン 2026',
      }),
    ],
  },
  {
    ...groups[5],
    events: [
      makeEvent(groups[5], {
        id: '2026-09-27-sumo-senshuraku',
        title: '大相撲九月場所 千秋楽',
        emoji: '🏯',
        categoryId: 'date',
        dateLabel: '9/27(日) 千秋楽',
        start: '2026-09-27T13:00:00+09:00',
        end: '2026-09-27T18:00:00+09:00',
        area: '両国',
        locationName: '両国国技館',
        nearestStation: '両国駅 徒歩約2分',
        price: 'チケット制',
        reservation: '前売券確認',
        rainFriendly: true,
        tags: ['屋内', '相撲', '和文化', '両国'],
        summary: '九月場所の最終日。盛り上がりは強いがチケット難度も高め。',
        coupleNote: '取れたら強い。取れない場合は両国散歩と江戸東京系の展示に切替。',
        sourceName: '日本相撲協会公式',
        url: 'https://www.sumo.or.jp/Watching/isolate/637/',
        imageQuery: '大相撲 九月場所 千秋楽 両国国技館',
      }),
      makeEvent(groups[5], {
        id: '2026-09-27-my-birthday',
        title: '「My Birthday」展',
        emoji: '🔮',
        categoryId: 'date',
        dateLabel: '9/27(日)まで',
        start: '2026-09-27T13:00:00+09:00',
        end: '2026-09-27T15:00:00+09:00',
        area: '根津・弥生',
        locationName: '弥生美術館',
        nearestStation: '根津駅・東大前駅',
        price: '一般1,200円',
        reservation: '公式確認',
        rainFriendly: true,
        tags: ['屋内', '展覧会', '占い', 'レトロ'],
        summary: '80から90年代の占いカルチャー少女雑誌を題材にした展覧会。',
        coupleNote: '軽めで会話にしやすい。根津、上野、谷中の散歩と相性が良い。',
        sourceName: '東京の観光公式サイト GO TOKYO',
        url: 'https://www.gotokyo.org/jp/see-and-do/arts-and-design/art-and-exhibitions/index.html',
        imageQuery: 'My Birthday展 弥生美術館',
      }),
      makeEvent(groups[5], {
        id: '2026-09-27-okura-prayer',
        title: '祈りと救いの美 国宝 普賢菩薩騎象像との出会い',
        emoji: '🪷',
        categoryId: 'date',
        dateLabel: '9/27(日)まで',
        start: '2026-09-27T13:00:00+09:00',
        end: '2026-09-27T15:00:00+09:00',
        area: '虎ノ門',
        locationName: '大倉集古館',
        nearestStation: '六本木一丁目駅・神谷町駅',
        price: '観覧料確認',
        reservation: '公式確認',
        rainFriendly: true,
        tags: ['屋内', '美術館', '仏教美術', '静か'],
        summary: '仏教美術の流れを紹介し、国宝の普賢菩薩騎象像も扱う展覧会。',
        coupleNote: '静かな屋内候補。麻布台ヒルズや虎ノ門の食事に寄せやすい。',
        sourceName: '東京の観光公式サイト GO TOKYO',
        url: 'https://www.gotokyo.org/jp/see-and-do/arts-and-design/art-and-exhibitions/index.html',
        imageQuery: '大倉集古館 祈りと救いの美 普賢菩薩騎象像',
      }),
    ],
  },
  {
    ...groups[6],
    events: [
      makeEvent(groups[6], {
        id: '2026-10-03-moon-art-night-shimokita',
        title: 'ムーンアートナイト下北沢2026',
        emoji: '🌕',
        categoryId: 'date',
        dateLabel: '10/4(日)まで',
        start: '2026-10-03T17:00:00+09:00',
        end: '2026-10-03T21:00:00+09:00',
        area: '下北沢',
        locationName: '下北沢エリア全域',
        nearestStation: '下北沢駅・東北沢駅・世田谷代田駅',
        price: '無料エリアあり。一部チケット制',
        reservation: '一部コンテンツはチケット確認',
        rainFriendly: false,
        tags: ['アート', '夜', '街歩き', '下北沢'],
        summary: '下北沢の街全体を会場に、月をテーマにしたアート、音楽、演劇、飲食を楽しむ17日間のフェス。',
        coupleNote: '夜の雰囲気が強い本命候補。食事とバーへ自然につなげられる。',
        sourceName: 'ムーンアートナイト下北沢公式',
        url: 'https://moonartnightfes.com/',
        imageQuery: 'ムーンアートナイト下北沢2026',
      }),
      makeEvent(groups[6], {
        id: '2026-10-03-nt-tokyo',
        title: 'NT東京2026',
        emoji: '🛠️',
        categoryId: 'date',
        dateLabel: '10/3(土)-10/4(日)',
        start: '2026-10-03T10:00:00+09:00',
        end: '2026-10-03T17:00:00+09:00',
        area: '北の丸公園',
        locationName: '科学技術館 催事場',
        nearestStation: '竹橋駅・九段下駅',
        price: '無料・出入り自由',
        reservation: '不要',
        rainFriendly: true,
        tags: ['無料', 'ものづくり', '屋内', '科学技術館'],
        summary: '電子工作、ロボット、クラフトなど「作ってみた」を集める展示イベント。',
        coupleNote: '技術系に寄るが無料で軽い。北の丸、神保町、東京駅方面に流しやすい。',
        sourceName: 'NT東京公式',
        url: 'https://nt-tokyo.org/about/',
        imageQuery: 'NT東京2026 科学技術館',
      }),
      makeEvent(groups[6], {
        id: '2026-10-04-nyandarake',
        title: 'にゃんだらけ21',
        emoji: '🐈',
        categoryId: 'date',
        dateLabel: '10/3(土)-10/4(日)',
        start: '2026-10-04T11:00:00+09:00',
        end: '2026-10-04T17:00:00+09:00',
        area: '浅草',
        locationName: '東京都立産業貿易センター台東館',
        nearestStation: '浅草駅 徒歩約5分',
        price: '前売800円、当日1,200円',
        reservation: '前売券確認',
        rainFriendly: true,
        tags: ['屋内', '猫', '浅草', '物販'],
        summary: '猫好き向けの祭典。猫グッズ、健康情報、ステージ企画などを楽しめる。',
        coupleNote: '浅草散歩とセットにできる。猫の生体イベントではない点は注意。',
        sourceName: 'にゃんだらけ公式',
        url: 'https://nyandarake.tokyo/21kaisaigaiyo',
        imageQuery: 'にゃんだらけ21 浅草',
      }),
    ],
  },
  {
    ...groups[7],
    events: [
      makeEvent(groups[7], {
        id: '2026-10-10-tokyo-yosakoi',
        title: '第27回 東京よさこい',
        emoji: '🪭',
        categoryId: 'date',
        dateLabel: '10/10(土)-10/11(日)',
        start: '2026-10-10T11:00:00+09:00',
        end: '2026-10-10T20:00:00+09:00',
        area: '池袋',
        locationName: '池袋駅周辺',
        nearestStation: '池袋駅',
        price: '観覧無料',
        reservation: '不要。混雑と交通規制を確認',
        rainFriendly: false,
        tags: ['無料', '祭り', '踊り', '池袋'],
        summary: '池袋を中心に開催される都内最大級のよさこい祭り。多数のチームが参加する。',
        coupleNote: '熱量重視の週末候補。池袋なので食事や屋内退避も作りやすい。',
        sourceName: '東京よさこい公式',
        url: 'https://tokyo-yosakoi.jp/',
        imageQuery: '東京よさこい 2026 池袋',
      }),
      makeEvent(groups[7], {
        id: '2026-10-10-kahaku-life',
        title: 'いきもの超ワールド展',
        emoji: '🦖',
        categoryId: 'date',
        dateLabel: '10/12(月祝)まで',
        start: '2026-10-10T13:00:00+09:00',
        end: '2026-10-10T15:30:00+09:00',
        area: '上野',
        locationName: '国立科学博物館',
        nearestStation: '上野駅',
        price: '一般2,300円程度。公式確認',
        reservation: 'チケット確認',
        rainFriendly: true,
        tags: ['屋内', '科学館', '上野', '生きもの'],
        summary: '国立科学博物館とNHK自然番組の特別展。生きものの進化と生存戦略を扱う。',
        coupleNote: '雨や暑さの代替に強い。上野公園と食事へつなげやすい。',
        sourceName: '東京の観光公式サイト GO TOKYO',
        url: 'https://www.gotokyo.org/en/see-and-do/arts-and-design/art-and-exhibitions/',
        imageQuery: 'いきもの超ワールド展 国立科学博物館',
      }),
      makeEvent(groups[7], {
        id: '2026-10-11-disney-halloween',
        title: '東京ディズニーランド ディズニー・ハロウィーン',
        emoji: '🎃',
        categoryId: 'date',
        dateLabel: '10/31(土)まで',
        start: '2026-10-11T09:00:00+09:00',
        end: '2026-10-11T21:00:00+09:00',
        area: '舞浜',
        locationName: '東京ディズニーランド',
        nearestStation: '舞浜駅',
        price: '1デーパスポート料金確認',
        reservation: 'チケット事前購入',
        rainFriendly: false,
        tags: ['ハロウィーン', 'テーマパーク', '舞浜'],
        summary: 'ヴィランズが主役のハロウィーンイベント。10月の定番高満足プラン。',
        coupleNote: 'この週は全身仮装対象外期間なので、仮装目的なら10月16日以降がよい。',
        sourceName: '東京ディズニーリゾート公式',
        url: 'https://www.tokyodisneyresort.jp/tdl/daily/calendar/20261004/',
        imageQuery: '東京ディズニーランド ハロウィーン 2026',
      }),
    ],
  },
  {
    ...groups[8],
    events: [
      makeEvent(groups[8], {
        id: '2026-10-17-global-festa',
        title: 'グローバルフェスタJAPAN2026',
        emoji: '🌍',
        categoryId: 'meal',
        dateLabel: '10/17(土)-10/18(日)',
        start: '2026-10-17T10:00:00+09:00',
        end: '2026-10-17T17:00:00+09:00',
        area: '新宿',
        locationName: '新宿住友ビル三角広場・新宿中央公園',
        nearestStation: '都庁前駅・新宿駅',
        price: '入場無料',
        reservation: '不要',
        rainFriendly: true,
        tags: ['無料', '国際交流', 'フード', '屋内あり'],
        summary: '世界のキッチンカー、国際協力団体、ステージを楽しめる無料イベント。',
        coupleNote: 'レベッカとの国際ネタに合う。屋内と屋外があり天候対応しやすい。',
        sourceName: 'グローバルフェスタJAPAN公式',
        url: 'https://gfjapan2026.jp/',
        imageQuery: 'グローバルフェスタJAPAN2026 新宿',
      }),
      makeEvent(groups[8], {
        id: '2026-10-18-british-museum-tobikan',
        title: '大英博物館日本美術コレクション 百花繚乱',
        emoji: '🌊',
        categoryId: 'date',
        dateLabel: '10/18(日)まで',
        start: '2026-10-18T13:00:00+09:00',
        end: '2026-10-18T15:30:00+09:00',
        area: '上野',
        locationName: '東京都美術館',
        nearestStation: '上野駅',
        price: '一般2,300円',
        reservation: 'チケット確認',
        rainFriendly: true,
        tags: ['屋内', '美術館', '上野', '日本美術'],
        summary: '大英博物館の日本美術コレクションから江戸絵画や浮世絵を紹介する大型展。',
        coupleNote: '日本文化を英独目線で話せるので相性が良い。最終日は混雑注意。',
        sourceName: '東京都美術館公式',
        url: 'https://www.tobikan.jp/exhibition/2026_britishmuseum.html',
        imageQuery: '大英博物館日本美術コレクション 百花繚乱 東京都美術館',
      }),
      makeEvent(groups[8], {
        id: '2026-10-18-disney-costume',
        title: 'ディズニー・ハロウィーン 全身仮装期間',
        emoji: '🧛',
        categoryId: 'date',
        dateLabel: '10/16(金)-10/31(土)',
        start: '2026-10-18T09:00:00+09:00',
        end: '2026-10-18T21:00:00+09:00',
        area: '舞浜',
        locationName: '東京ディズニーリゾート',
        nearestStation: '舞浜駅',
        price: 'パークチケット料金確認',
        reservation: 'チケット事前購入',
        rainFriendly: false,
        tags: ['ハロウィーン', '仮装', 'テーマパーク'],
        summary: '10月16日から全身仮装可能期間。ハロウィーンらしさを強く出せる。',
        coupleNote: '準備が要るが記念写真には強い。ルール確認と着替え場所なしに注意。',
        sourceName: '東京ディズニーリゾート公式',
        url: 'https://www.tokyodisneyresort.jp/dream/event/costumes2026.html',
        imageQuery: '東京ディズニーリゾート ハロウィーン 仮装 2026',
      }),
    ],
  },
  {
    ...groups[9],
    events: [
      makeEvent(groups[9], {
        id: '2026-10-24-tokyo-night-market',
        title: '東京ナイトマーケット',
        emoji: '🌃',
        categoryId: 'meal',
        dateLabel: '10/24(土)-10/25(日)',
        start: '2026-10-24T14:00:00+09:00',
        end: '2026-10-24T22:00:00+09:00',
        area: '代々木',
        locationName: '代々木公園 ケヤキ並木',
        nearestStation: '原宿駅・明治神宮前駅',
        price: '入場無料。飲食は有料',
        reservation: '不要',
        rainFriendly: false,
        tags: ['無料入場', '夜', '屋台', '音楽'],
        summary: '40軒以上の屋台、ライブ、DJなどを楽しめる夜市。土日は14時から22時まで。',
        coupleNote: '10月後半の本命。夕方から入って渋谷、原宿へ流せる。',
        sourceName: '東京ナイトマーケット公式',
        url: 'https://tokyo-night-market.com/',
        imageQuery: '東京ナイトマーケット 2026 代々木公園',
      }),
      makeEvent(groups[9], {
        id: '2026-10-24-tokyo-grand-tea',
        title: '東京大茶会2026',
        emoji: '🍵',
        categoryId: 'date',
        dateLabel: '10/24(土)-10/25(日)',
        start: '2026-10-24T11:00:00+09:00',
        end: '2026-10-24T16:00:00+09:00',
        area: '小金井',
        locationName: '江戸東京たてもの園',
        nearestStation: '武蔵小金井駅・花小金井駅からバス',
        price: '公式確認',
        reservation: 'プログラムにより確認',
        rainFriendly: false,
        tags: ['茶道', '和文化', '庭園', '秋'],
        summary: '誰でも気軽にお茶の文化を楽しめる伝統文化イベント。',
        coupleNote: '日本文化体験として強い。少し遠いので半日確保。',
        sourceName: 'アーツカウンシル東京 伝統文化事業',
        url: 'https://www.tokyo-tradition.jp/2026/',
        imageQuery: '東京大茶会2026 江戸東京たてもの園',
      }),
      makeEvent(groups[9], {
        id: '2026-10-24-disney-halloween',
        title: '東京ディズニーランド ディズニー・ハロウィーン',
        emoji: '🎃',
        categoryId: 'date',
        dateLabel: '10/31(土)まで',
        start: '2026-10-24T09:00:00+09:00',
        end: '2026-10-24T21:00:00+09:00',
        area: '舞浜',
        locationName: '東京ディズニーランド',
        nearestStation: '舞浜駅',
        price: '1デーパスポート料金確認',
        reservation: 'チケット事前購入',
        rainFriendly: false,
        tags: ['ハロウィーン', '仮装', 'テーマパーク'],
        summary: 'ハロウィーン終盤の週末。全身仮装可能期間にも入っている。',
        coupleNote: '高いが記念感は最強。混雑とチケット価格を見て早めに判断。',
        sourceName: '東京ディズニーリゾート公式',
        url: 'https://www.tokyodisneyresort.jp/tdl/daily/calendar/20261024/',
        imageQuery: '東京ディズニーランド ハロウィーン 2026',
      }),
    ],
  },
];

function toDateOnly(value: Date): string {
  const year = value.getFullYear();
  const month = String(value.getMonth() + 1).padStart(2, '0');
  const day = String(value.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

export function upcomingWeekendEventGroups(now = new Date()): WeekendEventGroup[] {
  const today = toDateOnly(now);
  return MONTHLY_WEEKEND_EVENTS.filter((group) => group.endsOn >= today).slice(0, 10);
}

function toTabLabel(value: string): string {
  const [, month, day] = value.split('-');
  return `${Number(month)}/${Number(day)}`;
}

export function weekendResearchToGroups(research: WeekendResearch | null): WeekendEventGroup[] {
  if (!research) return [];

  const key = research.targetWeekend.start;
  const tabLabel = `${toTabLabel(research.targetWeekend.start)}-${toTabLabel(research.targetWeekend.end)}`;

  return [
    {
      key,
      label: research.targetWeekend.label,
      tabLabel,
      startsOn: research.targetWeekend.start,
      endsOn: research.targetWeekend.end,
      events: research.items.map((item) => ({
        id: item.id,
        weekendKey: key,
        weekendLabel: research.targetWeekend.label,
        tabLabel,
        title: item.title,
        emoji: item.emoji,
        categoryId: item.categoryId,
        dateLabel: item.dateLabel,
        start: item.start,
        end: item.end,
        area: item.area,
        locationName: item.locationName,
        nearestStation: item.nearestStation,
        price: item.price,
        reservation: item.reservation,
        rainFriendly: item.rainFriendly,
        tags: item.tags,
        summary: item.summary,
        coupleNote: item.coupleNote,
        sourceName: item.sourceName,
        url: item.url,
        imageUrl: item.imageUrl ?? undefined,
        imageQuery: `${item.title} ${item.locationName}`.trim(),
      })),
    },
  ];
}

export function weekendEventToInitial(item: WeekendEventPick): Partial<EventFormValue> {
  return weekendEventToInitialWithResearch(item);
}

export function weekendEventToFeedbackItem(item: WeekendEventPick): WeekendResearchItem {
  return weekendEventToFeedbackItemWithResearch(item);
}

export function weekendEventToInitialWithResearch(item: WeekendEventPick): Partial<EventFormValue> {
  return {
    title: `${item.emoji} ${item.title}`,
    description: [
      item.summary,
      '',
      `日程: ${item.dateLabel}`,
      `エリア: ${item.area}`,
      `最寄り: ${item.nearestStation}`,
      `料金: ${item.price}`,
      `予約: ${item.reservation}`,
      `雨天対応: ${item.rainFriendly ? '屋内または雨でも使いやすい' : '天候確認が必要'}`,
      '',
      item.coupleNote ?? item.summary,
      '',
      `出典: ${item.sourceName}`,
      item.url,
    ].join('\n'),
    location: item.locationName,
    start: new Date(item.start).toISOString(),
    end: new Date(item.end).toISOString(),
    reminderMinutes: 60,
    color: null,
    emoji: item.emoji,
    categoryId: item.categoryId,
    mapsPlaceId: null,
    recurrence: { frequency: 'none', count: 1 },
    visibility: 'shared',
  };
}

export function weekendEventToFeedbackItemWithResearch(item: WeekendEventPick): WeekendResearchItem {
  return {
    id: item.id,
    title: item.title,
    emoji: item.emoji,
    categoryId: item.categoryId,
    dateLabel: item.dateLabel,
    start: item.start,
    end: item.end,
    area: item.area,
    locationName: item.locationName,
    nearestStation: item.nearestStation,
    price: item.price,
    reservation: item.reservation,
    rainFriendly: item.rainFriendly ?? item.tags.includes('屋内'),
    tags: item.tags,
    summary: item.summary,
    coupleNote: item.coupleNote ?? item.summary,
    sourceName: item.sourceName,
    url: item.url,
    imageUrl: item.imageUrl ?? null,
  };
}
