import type { EventFormValue } from '@/components/calendar/EventModal';
import type { WeekendResearch, WeekendResearchItem } from '@/hooks/useWeekendResearch';

export interface WeekendEventPick {
  id: string;
  weekendKey: string;
  weekendLabel: string;
  tabLabel: string;
  title: string;
  emoji: string;
  categoryId: string;
  dateLabel: string;
  start: string;
  end: string;
  area: string;
  locationName: string;
  nearestStation: string;
  price: string;
  reservation: string;
  rainFriendly?: boolean;
  tags: string[];
  summary: string;
  coupleNote?: string;
  sourceName: string;
  url: string;
  imageUrl?: string;
  imageQuery: string;
}

export interface WeekendEventGroup {
  key: string;
  label: string;
  tabLabel: string;
  startsOn: string;
  endsOn: string;
  events: WeekendEventPick[];
}

type WeekendEventInput = Omit<WeekendEventPick, 'weekendKey' | 'weekendLabel' | 'tabLabel'>;

const makeEvent = (group: Omit<WeekendEventGroup, 'events'>, item: WeekendEventInput): WeekendEventPick => ({
  ...item,
  weekendKey: group.key,
  weekendLabel: group.label,
  tabLabel: group.tabLabel,
});

const weekendGroup = (meta: Omit<WeekendEventGroup, 'events'>, events: WeekendEventInput[]): WeekendEventGroup => ({
  ...meta,
  events: events.map((event) => makeEvent(meta, event)),
});

export const MONTHLY_WEEKEND_EVENTS: WeekendEventGroup[] = [
  weekendGroup(
    {
      key: '2026-09-05',
      label: '2026/09/05(土)-09/06(日)',
      tabLabel: '9/5-6',
      startsOn: '2026-09-05',
      endsOn: '2026-09-06',
    },
    [
      {
        id: '2026-09-05-china-festival-yoyogi',
        title: 'チャイナフェスティバル2026 代々木',
        emoji: '🐼',
        categoryId: 'meal',
        dateLabel: '9/5(土)-9/6(日)',
        start: '2026-09-05T10:00:00+09:00',
        end: '2026-09-05T20:00:00+09:00',
        area: '代々木公園',
        locationName: '代々木公園 イベント広場・ケヤキ並木',
        nearestStation: '原宿駅 / 明治神宮前駅 / 代々木公園駅',
        price: '入場無料。飲食・物販は有料',
        reservation: '不要。雨天決行、荒天中止',
        rainFriendly: false,
        tags: ['無料', 'フード', '文化交流', '代々木公園'],
        summary: '中国の食、文化、ステージをまとめて楽しめる大型フェス。10時から20時まで開くので、昼の食べ歩きにも夜の散歩にも使いやすいです。',
        coupleNote: '暑さが残る時期なので、夕方から行って代々木公園と表参道をつなぐのが無難です。',
        sourceName: 'チャイナフェスティバル2026公式',
        url: 'https://www.chinafes.net/yoyogi/',
        imageUrl: 'https://www.chinafes.net/wp-content/uploads/2026/03/chifes-logo.png',
        imageQuery: 'チャイナフェスティバル2026 代々木 公式',
      },
      {
        id: '2026-09-05-yokohama-night-flowers',
        title: '横浜ナイトフラワーズ2026',
        emoji: '🎆',
        categoryId: 'date',
        dateLabel: '9/5(土) 夜',
        start: '2026-09-05T19:00:00+09:00',
        end: '2026-09-05T19:20:00+09:00',
        area: 'みなとみらい',
        locationName: '横浜港 新港ふ頭周辺',
        nearestStation: 'みなとみらい駅 / 馬車道駅 / 桜木町駅',
        price: '無料',
        reservation: '不要。天候や当日案内を確認',
        rainFriendly: false,
        tags: ['無料', '花火', '夜景', '横浜'],
        summary: '横浜港で5分程度打ち上がる短時間花火。19時からなので、夕食前後のワンポイント予定として組み込みやすいです。',
        coupleNote: '短時間なので、赤レンガ倉庫、ワールドポーターズ、みなとみらい散歩とセットにするのが前提です。',
        sourceName: '横浜市観光公式サイト',
        url: 'https://www.welcome.city.yokohama.jp/spring_special/event/ev_detail.php?bid=yw11005',
        imageUrl: 'https://ycvb.yokohama/img_data/yw10951_1.jpg',
        imageQuery: '横浜ナイトフラワーズ2026 公式',
      },
      {
        id: '2026-09-05-gotoh-karakusa',
        title: '五島美術館 秋の優品展「唐草文の美」',
        emoji: '🏺',
        categoryId: 'date',
        dateLabel: '9/5(土) 開幕',
        start: '2026-09-06T11:00:00+09:00',
        end: '2026-09-06T13:00:00+09:00',
        area: '上野毛',
        locationName: '五島美術館',
        nearestStation: '上野毛駅',
        price: '一般1,100円',
        reservation: '不要。開館日と展示替えを確認',
        rainFriendly: true,
        tags: ['屋内', '美術館', '庭園', '静か'],
        summary: '五島美術館の収蔵品から、唐草文をテーマに古鏡、陶磁、染織などを見る展覧会。庭園とセットで静かな週末に向きます。',
        coupleNote: '混雑イベントを避けたい時の安全候補。二子玉川や自由が丘方面のカフェに流しやすいです。',
        sourceName: '五島美術館公式',
        url: 'https://www.gotoh-museum.or.jp/event/next/',
        imageUrl: 'https://www.gotoh-museum.or.jp/wp-content/uploads/2026/05/2026_0905-img01.png',
        imageQuery: '五島美術館 唐草文の美 公式',
      },
    ],
  ),
  weekendGroup(
    {
      key: '2026-09-12',
      label: '2026/09/12(土)-09/13(日)',
      tabLabel: '9/12-13',
      startsOn: '2026-09-12',
      endsOn: '2026-09-13',
    },
    [
      {
        id: '2026-09-12-showa-cosmos',
        title: '国営昭和記念公園 コスモスまつり2026',
        emoji: '🌼',
        categoryId: 'date',
        dateLabel: '9/12(土) 開幕',
        start: '2026-09-13T11:00:00+09:00',
        end: '2026-09-13T15:00:00+09:00',
        area: '立川',
        locationName: '国営昭和記念公園',
        nearestStation: '西立川駅 / 立川駅',
        price: '入園料確認',
        reservation: '不要。開花状況を確認',
        rainFriendly: false,
        tags: ['花', '公園', '写真', '立川'],
        summary: '9月12日から10月25日まで開催。レモンブライト、ブーケガーデン、センセーションなど、複数の花畑を時期ごとに楽しめます。',
        coupleNote: '半日しっかり歩く前提。暑い日は午前寄り、雨なら別候補へ切り替えです。',
        sourceName: '国営昭和記念公園公式',
        url: 'https://www.showakinen-koen.jp/cosmos-festival/',
        imageUrl: 'https://www.showakinen-koen.jp/cosmos-festival/images/hero.webp',
        imageQuery: '昭和記念公園 コスモスまつり2026 公式',
      },
      {
        id: '2026-09-13-september-sumo',
        title: '大相撲九月場所',
        emoji: '🏟️',
        categoryId: 'date',
        dateLabel: '9/13(日) 初日',
        start: '2026-09-13T14:00:00+09:00',
        end: '2026-09-13T18:00:00+09:00',
        area: '両国',
        locationName: '両国国技館',
        nearestStation: '両国駅',
        price: '席種別。公式で確認',
        reservation: 'チケット確認必須',
        rainFriendly: true,
        tags: ['屋内', '相撲', '両国', '体験'],
        summary: '9月13日から27日まで両国国技館で開催される本場所。屋内で天気に左右されず、両国の食事と組み合わせやすいです。',
        coupleNote: 'チケット前提なので、空席が取れるかを先に確認する候補です。',
        sourceName: '日本相撲協会公式',
        url: 'https://sumo.or.jp/Watching/isolate/637/',
        imageUrl: 'https://sumo.or.jp/img/watching/tokyo.gif',
        imageQuery: '大相撲九月場所 両国国技館 公式',
      },
    ],
  ),
  weekendGroup(
    {
      key: '2026-09-19',
      label: '2026/09/19(土)-09/21(月祝)',
      tabLabel: '9/19-21',
      startsOn: '2026-09-19',
      endsOn: '2026-09-21',
    },
    [
      {
        id: '2026-09-19-tokyo-game-show',
        title: '東京ゲームショウ2026 一般公開日',
        emoji: '🎮',
        categoryId: 'date',
        dateLabel: '9/19(土)-9/21(月祝)',
        start: '2026-09-19T09:30:00+09:00',
        end: '2026-09-19T17:00:00+09:00',
        area: '幕張',
        locationName: '幕張メッセ',
        nearestStation: '海浜幕張駅',
        price: 'チケット制。公式で確認',
        reservation: 'チケット確認必須',
        rainFriendly: true,
        tags: ['屋内', 'ゲーム', '大型イベント', '幕張'],
        summary: 'TGS 2026は9月17日から21日まで開催。一般公開日は9月19日、20日、21日の3日間です。',
        coupleNote: '人混み前提。ゲーム好きなら強いが、移動と待機時間を長めに見る必要があります。',
        sourceName: '東京ゲームショウ公式',
        url: 'https://tgs.cesa.or.jp/2026/',
        imageUrl: 'https://tgs.cesa.or.jp/2026/images/home/overview_theme.png',
        imageQuery: '東京ゲームショウ2026 公式',
      },
      {
        id: '2026-09-19-moon-art-night',
        title: 'ムーンアートナイト下北沢2026',
        emoji: '🌕',
        categoryId: 'date',
        dateLabel: '9/18(金)-10/4(日)',
        start: '2026-09-19T18:00:00+09:00',
        end: '2026-09-19T21:00:00+09:00',
        area: '下北沢',
        locationName: '下北沢エリア全域・下北線路街',
        nearestStation: '下北沢駅 / 東北沢駅',
        price: '一部チケット制。無料鑑賞エリアあり',
        reservation: '有料作品はチケット確認',
        rainFriendly: false,
        tags: ['アート', '夜散歩', '下北沢', '写真'],
        summary: '下北沢の街全体を使うアートフェス。巨大な月のアートや街歩き型の展示を夜に楽しめます。',
        coupleNote: '夜散歩と食事の相性がよい候補。下北沢で夕食まで完結できます。',
        sourceName: 'ムーンアートナイト下北沢公式',
        url: 'https://moonartnightfes.com/',
        imageUrl: 'https://moonartnightfes.com/img/hero.png',
        imageQuery: 'ムーンアートナイト下北沢2026 公式',
      },
      {
        id: '2026-09-20-yokohama-night-flowers',
        title: '横浜ナイトフラワーズ2026',
        emoji: '🎆',
        categoryId: 'date',
        dateLabel: '9/20(日) 夜',
        start: '2026-09-20T19:00:00+09:00',
        end: '2026-09-20T19:20:00+09:00',
        area: 'みなとみらい',
        locationName: '横浜港 大さん橋周辺',
        nearestStation: '日本大通り駅 / 馬車道駅',
        price: '無料',
        reservation: '不要。天候や当日案内を確認',
        rainFriendly: false,
        tags: ['無料', '花火', '夜景', '横浜'],
        summary: '9月20日は大さん橋周辺で19時から5分程度の短時間花火。みなとみらい散歩に足しやすいです。',
        coupleNote: 'メイン目的というより、横浜デートの締めに入れる候補です。',
        sourceName: '横浜市観光公式サイト',
        url: 'https://www.welcome.city.yokohama.jp/spring_special/event/ev_detail.php?bid=yw11005',
        imageUrl: 'https://ycvb.yokohama/img_data/yw10951_1.jpg',
        imageQuery: '横浜ナイトフラワーズ2026 公式',
      },
    ],
  ),
  weekendGroup(
    {
      key: '2026-09-26',
      label: '2026/09/26(土)-09/27(日)',
      tabLabel: '9/26-27',
      startsOn: '2026-09-26',
      endsOn: '2026-09-27',
    },
    [
      {
        id: '2026-09-26-september-sumo-final-weekend',
        title: '大相撲九月場所 終盤週末',
        emoji: '🏟️',
        categoryId: 'date',
        dateLabel: '9/26(土)-9/27(日)',
        start: '2026-09-26T14:00:00+09:00',
        end: '2026-09-26T18:00:00+09:00',
        area: '両国',
        locationName: '両国国技館',
        nearestStation: '両国駅',
        price: '席種別。公式で確認',
        reservation: 'チケット確認必須',
        rainFriendly: true,
        tags: ['屋内', '相撲', '両国', '終盤'],
        summary: '九月場所は9月27日まで。終盤週末なので盛り上がりやすい一方、チケット確保は早めが必要です。',
        coupleNote: '取れたら強い屋内候補。両国でちゃんこや和食に流すと予定としてまとまります。',
        sourceName: '日本相撲協会公式',
        url: 'https://sumo.or.jp/Watching/isolate/637/',
        imageUrl: 'https://sumo.or.jp/img/watching/tokyo.gif',
        imageQuery: '大相撲九月場所 両国国技館 公式',
      },
      {
        id: '2026-09-26-showa-cosmos',
        title: '国営昭和記念公園 コスモスまつり2026',
        emoji: '🌼',
        categoryId: 'date',
        dateLabel: '開催中',
        start: '2026-09-27T11:00:00+09:00',
        end: '2026-09-27T15:00:00+09:00',
        area: '立川',
        locationName: '国営昭和記念公園',
        nearestStation: '西立川駅 / 立川駅',
        price: '入園料確認',
        reservation: '不要。開花状況を確認',
        rainFriendly: false,
        tags: ['花', '公園', '写真', '立川'],
        summary: '9月下旬はブーケガーデンやレモンブライトを狙える時期。晴れた日の昼デート向けです。',
        coupleNote: '歩く距離が長いので、スニーカー前提。帰りは立川駅周辺で食事が組みやすいです。',
        sourceName: '国営昭和記念公園公式',
        url: 'https://www.showakinen-koen.jp/cosmos-festival/',
        imageUrl: 'https://www.showakinen-koen.jp/cosmos-festival/images/hero.webp',
        imageQuery: '昭和記念公園 コスモスまつり2026 公式',
      },
      {
        id: '2026-09-26-moon-art-night',
        title: 'ムーンアートナイト下北沢2026',
        emoji: '🌕',
        categoryId: 'date',
        dateLabel: '開催中',
        start: '2026-09-26T18:00:00+09:00',
        end: '2026-09-26T21:00:00+09:00',
        area: '下北沢',
        locationName: '下北沢エリア全域・下北線路街',
        nearestStation: '下北沢駅 / 東北沢駅',
        price: '一部チケット制。無料鑑賞エリアあり',
        reservation: '有料作品はチケット確認',
        rainFriendly: false,
        tags: ['アート', '夜散歩', '下北沢', '写真'],
        summary: '会期中盤の週末。作品を見ながら下北沢の飲食店も回れる夜デート候補です。',
        coupleNote: '人混みが強い場合も、店の選択肢が多いのでリカバリーしやすいです。',
        sourceName: 'ムーンアートナイト下北沢公式',
        url: 'https://moonartnightfes.com/',
        imageUrl: 'https://moonartnightfes.com/img/hero.png',
        imageQuery: 'ムーンアートナイト下北沢2026 公式',
      },
    ],
  ),
  weekendGroup(
    {
      key: '2026-10-03',
      label: '2026/10/03(土)-10/04(日)',
      tabLabel: '10/3-4',
      startsOn: '2026-10-03',
      endsOn: '2026-10-04',
    },
    [
      {
        id: '2026-10-03-moon-art-night-final-weekend',
        title: 'ムーンアートナイト下北沢2026 最終週末',
        emoji: '🌕',
        categoryId: 'date',
        dateLabel: '10/4(日)まで',
        start: '2026-10-03T18:00:00+09:00',
        end: '2026-10-03T21:00:00+09:00',
        area: '下北沢',
        locationName: '下北沢エリア全域・下北線路街',
        nearestStation: '下北沢駅 / 東北沢駅',
        price: '一部チケット制。無料鑑賞エリアあり',
        reservation: '有料作品はチケット確認',
        rainFriendly: false,
        tags: ['アート', '夜散歩', '最終週末', '下北沢'],
        summary: '10月4日までの最終週末。見逃し防止の候補として優先度高めです。',
        coupleNote: '夜に軽く予定を作りたい時に使いやすいです。食事予約なしでも逃げ道が多いです。',
        sourceName: 'ムーンアートナイト下北沢公式',
        url: 'https://moonartnightfes.com/',
        imageUrl: 'https://moonartnightfes.com/img/hero.png',
        imageQuery: 'ムーンアートナイト下北沢2026 公式',
      },
      {
        id: '2026-10-03-gotoh-national-treasure',
        title: '五島美術館 唐草文の美 国宝特別展示期間',
        emoji: '🏺',
        categoryId: 'date',
        dateLabel: '10/3(土)-10/12(月祝)',
        start: '2026-10-04T11:00:00+09:00',
        end: '2026-10-04T13:00:00+09:00',
        area: '上野毛',
        locationName: '五島美術館',
        nearestStation: '上野毛駅',
        price: '一般1,100円',
        reservation: '不要。開館日を確認',
        rainFriendly: true,
        tags: ['屋内', '美術館', '国宝', '庭園'],
        summary: '10月3日から国宝「紫式部日記絵巻」五島本の特別展示期間。美術館デートとして価値が上がる週末です。',
        coupleNote: '静かに過ごしたい日に向きます。上野毛から二子玉川方面へ移動すると食事も作りやすいです。',
        sourceName: '五島美術館公式',
        url: 'https://www.gotoh-museum.or.jp/event/next/',
        imageUrl: 'https://www.gotoh-museum.or.jp/wp-content/uploads/2026/05/2026_0905-img01.png',
        imageQuery: '五島美術館 唐草文の美 公式',
      },
      {
        id: '2026-10-03-showa-cosmos',
        title: '国営昭和記念公園 コスモスまつり2026',
        emoji: '🌼',
        categoryId: 'date',
        dateLabel: '開催中',
        start: '2026-10-04T11:00:00+09:00',
        end: '2026-10-04T15:00:00+09:00',
        area: '立川',
        locationName: '国営昭和記念公園',
        nearestStation: '西立川駅 / 立川駅',
        price: '入園料確認',
        reservation: '不要。開花状況を確認',
        rainFriendly: false,
        tags: ['花', '公園', '写真', '立川'],
        summary: '10月上旬はセンセーションや赤ソバの時期にも入り、秋の花畑を狙いやすいです。',
        coupleNote: '天気がよい日の昼候補。写真を撮るなら午前から昼過ぎが無難です。',
        sourceName: '国営昭和記念公園公式',
        url: 'https://www.showakinen-koen.jp/cosmos-festival/',
        imageUrl: 'https://www.showakinen-koen.jp/cosmos-festival/images/hero.webp',
        imageQuery: '昭和記念公園 コスモスまつり2026 公式',
      },
    ],
  ),
  weekendGroup(
    {
      key: '2026-10-10',
      label: '2026/10/10(土)-10/12(月祝)',
      tabLabel: '10/10-12',
      startsOn: '2026-10-10',
      endsOn: '2026-10-12',
    },
    [
      {
        id: '2026-10-10-tokyo-yosakoi',
        title: '第27回 東京よさこい',
        emoji: '鳴',
        categoryId: 'date',
        dateLabel: '10/10(土)-10/11(日)',
        start: '2026-10-10T12:00:00+09:00',
        end: '2026-10-10T18:00:00+09:00',
        area: '池袋',
        locationName: '池袋駅周辺各会場',
        nearestStation: '池袋駅',
        price: '観覧無料想定。公式案内確認',
        reservation: '不要想定。演舞スケジュール確認',
        rainFriendly: false,
        tags: ['祭り', '踊り', '池袋', '無料あり'],
        summary: '池袋を中心に開催される都内最大級のよさこい祭り。10月10日と11日の2日開催です。',
        coupleNote: '池袋で食事やカフェに逃げやすいので、混雑しても予定を崩しにくい候補です。',
        sourceName: '東京よさこい公式',
        url: 'https://tokyo-yosakoi.jp/',
        imageUrl: 'https://tokyo-yosakoi.jp/wp-content/themes/yosakoitokyo/assets/img/fv_pc.png',
        imageQuery: '東京よさこい2026 公式',
      },
      {
        id: '2026-10-11-yokohama-night-flowers',
        title: '横浜ナイトフラワーズ2026',
        emoji: '🎆',
        categoryId: 'date',
        dateLabel: '10/11(日) 夜',
        start: '2026-10-11T19:00:00+09:00',
        end: '2026-10-11T19:20:00+09:00',
        area: 'みなとみらい',
        locationName: '横浜港 大さん橋周辺',
        nearestStation: '日本大通り駅 / 馬車道駅',
        price: '無料',
        reservation: '不要。天候や当日案内を確認',
        rainFriendly: false,
        tags: ['無料', '花火', '夜景', '横浜'],
        summary: '10月11日は大さん橋周辺で19時から短時間花火。三連休の横浜夜デートに入れやすいです。',
        coupleNote: '中華街、赤レンガ、みなとみらいのどれとも組み合わせやすいです。',
        sourceName: '横浜市観光公式サイト',
        url: 'https://www.welcome.city.yokohama.jp/spring_special/event/ev_detail.php?bid=yw11005',
        imageUrl: 'https://ycvb.yokohama/img_data/yw10951_1.jpg',
        imageQuery: '横浜ナイトフラワーズ2026 公式',
      },
      {
        id: '2026-10-10-showa-cosmos',
        title: '国営昭和記念公園 コスモスまつり2026',
        emoji: '🌼',
        categoryId: 'date',
        dateLabel: '開催中',
        start: '2026-10-12T11:00:00+09:00',
        end: '2026-10-12T15:00:00+09:00',
        area: '立川',
        locationName: '国営昭和記念公園',
        nearestStation: '西立川駅 / 立川駅',
        price: '入園料確認',
        reservation: '不要。開花状況を確認',
        rainFriendly: false,
        tags: ['花', '公園', '写真', '立川'],
        summary: '10月の連休に使える花畑候補。晴れれば満足度が高い一方、混雑は見込みます。',
        coupleNote: '広いので現地で混雑分散しやすいです。帰りの立川駅混雑だけ注意です。',
        sourceName: '国営昭和記念公園公式',
        url: 'https://www.showakinen-koen.jp/cosmos-festival/',
        imageUrl: 'https://www.showakinen-koen.jp/cosmos-festival/images/hero.webp',
        imageQuery: '昭和記念公園 コスモスまつり2026 公式',
      },
    ],
  ),
  weekendGroup(
    {
      key: '2026-10-17',
      label: '2026/10/17(土)-10/18(日)',
      tabLabel: '10/17-18',
      startsOn: '2026-10-17',
      endsOn: '2026-10-18',
    },
    [
      {
        id: '2026-10-17-global-festa-japan',
        title: 'グローバルフェスタJAPAN2026',
        emoji: '🌍',
        categoryId: 'meal',
        dateLabel: '10/17(土)-10/18(日)',
        start: '2026-10-17T10:00:00+09:00',
        end: '2026-10-17T17:00:00+09:00',
        area: '西新宿',
        locationName: '新宿住友ビル三角広場・新宿中央公園',
        nearestStation: '都庁前駅 / 新宿駅',
        price: '入場無料',
        reservation: '不要想定。公式案内確認',
        rainFriendly: true,
        tags: ['無料', '国際協力', 'フード', '屋内あり'],
        summary: '国際協力やSDGsに取り組む団体が集まるイベント。屋内会場と屋外会場があり、世界の食やワークショップも楽しめます。',
        coupleNote: '新宿完結で雨にも強い候補。軽く見てからカフェや映画に切り替えやすいです。',
        sourceName: 'グローバルフェスタJAPAN2026公式',
        url: 'https://gfjapan2026.jp/',
        imageUrl: 'https://gfjapan2026.jp/assets/img/img_kv.jpg',
        imageQuery: 'グローバルフェスタJAPAN2026 公式',
      },
      {
        id: '2026-10-17-showa-cosmos',
        title: '国営昭和記念公園 コスモスまつり2026',
        emoji: '🌼',
        categoryId: 'date',
        dateLabel: '開催中',
        start: '2026-10-18T11:00:00+09:00',
        end: '2026-10-18T15:00:00+09:00',
        area: '立川',
        locationName: '国営昭和記念公園',
        nearestStation: '西立川駅 / 立川駅',
        price: '入園料確認',
        reservation: '不要。開花状況を確認',
        rainFriendly: false,
        tags: ['花', '公園', '写真', '立川'],
        summary: '10月後半はセンセーションや赤ソバ、コキアの色づきも狙える時期です。',
        coupleNote: '秋らしい写真を撮るならこの週も有力。天気確認必須です。',
        sourceName: '国営昭和記念公園公式',
        url: 'https://www.showakinen-koen.jp/cosmos-festival/',
        imageUrl: 'https://www.showakinen-koen.jp/cosmos-festival/images/hero.webp',
        imageQuery: '昭和記念公園 コスモスまつり2026 公式',
      },
    ],
  ),
  weekendGroup(
    {
      key: '2026-10-24',
      label: '2026/10/24(土)-10/25(日)',
      tabLabel: '10/24-25',
      startsOn: '2026-10-24',
      endsOn: '2026-10-25',
    },
    [
      {
        id: '2026-10-24-tokyo-night-market',
        title: '東京ナイトマーケット',
        emoji: '🌃',
        categoryId: 'meal',
        dateLabel: '10/24(土)-10/25(日)',
        start: '2026-10-24T16:00:00+09:00',
        end: '2026-10-24T22:00:00+09:00',
        area: '代々木公園',
        locationName: '代々木公園 ケヤキ並木',
        nearestStation: '原宿駅 / 明治神宮前駅 / 代々木公園駅',
        price: '入場無料。飲食は有料',
        reservation: '不要想定。公式案内確認',
        rainFriendly: false,
        tags: ['無料', 'ナイトマーケット', '屋台', '代々木'],
        summary: '10月21日から25日まで、代々木公園ケヤキ並木で開催。土日は14時から22時までです。',
        coupleNote: '夕方から夜の軽い予定に強い候補。食べ歩きと音楽を合わせやすいです。',
        sourceName: '東京ナイトマーケット公式',
        url: 'https://tokyo-night-market.com/',
        imageUrl: 'https://tokyo-night-market.com/wp-content/uploads/2026/07/2026l.png',
        imageQuery: '東京ナイトマーケット 2026 公式',
      },
      {
        id: '2026-10-24-tokyo-grand-tea-ceremony',
        title: '東京大茶会2026 江戸東京たてもの園',
        emoji: '🍵',
        categoryId: 'date',
        dateLabel: '10/24(土)-10/25(日)',
        start: '2026-10-25T10:30:00+09:00',
        end: '2026-10-25T16:00:00+09:00',
        area: '小金井',
        locationName: '江戸東京たてもの園',
        nearestStation: '武蔵小金井駅 / 花小金井駅',
        price: '入園無料。茶席は有料プログラムあり',
        reservation: '茶席は当日販売。公式案内確認',
        rainFriendly: false,
        tags: ['茶会', '江戸文化', '小金井', '秋'],
        summary: '江戸東京たてもの園で開催される大規模なお茶会。茶道初心者でも参加しやすい秋の伝統文化イベントです。',
        coupleNote: '落ち着いた秋デート向け。小金井公園散歩と合わせると半日予定になります。',
        sourceName: 'アーツカウンシル東京 伝統文化事業公式',
        url: 'https://www.tokyo-tradition.jp/2026/',
        imageUrl: 'https://www.tokyo-tradition.jp/2026/images/photo-ocha.webp',
        imageQuery: '東京大茶会2026 公式',
      },
      {
        id: '2026-10-24-yokohama-night-flowers',
        title: '横浜ナイトフラワーズ2026',
        emoji: '🎆',
        categoryId: 'date',
        dateLabel: '10/24(土) 夜',
        start: '2026-10-24T19:00:00+09:00',
        end: '2026-10-24T19:20:00+09:00',
        area: 'みなとみらい',
        locationName: '横浜港 新港ふ頭周辺',
        nearestStation: 'みなとみらい駅 / 馬車道駅 / 桜木町駅',
        price: '無料',
        reservation: '不要。天候や当日案内を確認',
        rainFriendly: false,
        tags: ['無料', '花火', '夜景', '横浜'],
        summary: '10月24日は新港ふ頭周辺で19時から短時間花火。横浜の夜景と合わせやすいです。',
        coupleNote: '東京ナイトマーケットとは方向が違うので、横浜に寄せたい週の候補です。',
        sourceName: '横浜市観光公式サイト',
        url: 'https://www.welcome.city.yokohama.jp/spring_special/event/ev_detail.php?bid=yw11005',
        imageUrl: 'https://ycvb.yokohama/img_data/yw10951_1.jpg',
        imageQuery: '横浜ナイトフラワーズ2026 公式',
      },
    ],
  ),
];

function toDateOnly(value: Date): string {
  const year = value.getFullYear();
  const month = String(value.getMonth() + 1).padStart(2, '0');
  const day = String(value.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

export function upcomingWeekendEventGroups(now = new Date()): WeekendEventGroup[] {
  const today = toDateOnly(now);
  return MONTHLY_WEEKEND_EVENTS.filter((group) => group.endsOn >= today);
}

function toTabLabel(value: string): string {
  const [, month, day] = value.split('-');
  return `${Number(month)}/${Number(day)}`;
}

export function weekendResearchToGroups(research: WeekendResearch | null): WeekendEventGroup[] {
  if (!research) return [];

  const key = research.targetWeekend.start;
  const tabLabel = `${toTabLabel(research.targetWeekend.start)}-${toTabLabel(research.targetWeekend.end)}`;

  return [
    {
      key,
      label: research.targetWeekend.label,
      tabLabel,
      startsOn: research.targetWeekend.start,
      endsOn: research.targetWeekend.end,
      events: research.items
        .filter((item) => Boolean(item.imageUrl?.trim()))
        .map((item) => ({
          id: item.id,
          weekendKey: key,
          weekendLabel: research.targetWeekend.label,
          tabLabel,
          title: item.title,
          emoji: item.emoji,
          categoryId: item.categoryId,
          dateLabel: item.dateLabel,
          start: item.start,
          end: item.end,
          area: item.area,
          locationName: item.locationName,
          nearestStation: item.nearestStation,
          price: item.price,
          reservation: item.reservation,
          rainFriendly: item.rainFriendly,
          tags: item.tags,
          summary: item.summary,
          coupleNote: item.coupleNote,
          sourceName: item.sourceName,
          url: item.url,
          imageUrl: item.imageUrl ?? undefined,
          imageQuery: `${item.title} ${item.locationName}`.trim(),
        })),
    },
  ].filter((group) => group.events.length > 0);
}

export function weekendEventToInitial(item: WeekendEventPick): Partial<EventFormValue> {
  return {
    title: `${item.emoji} ${item.title}`,
    description: [
      item.summary,
      '',
      `日程: ${item.dateLabel}`,
      `エリア: ${item.area}`,
      `最寄り: ${item.nearestStation}`,
      `料金: ${item.price}`,
      `予約: ${item.reservation}`,
      `出典: ${item.sourceName}`,
      item.url,
    ].join('\n'),
    location: item.locationName,
    start: new Date(item.start).toISOString(),
    end: new Date(item.end).toISOString(),
    reminderMinutes: 60,
    color: null,
    emoji: item.emoji,
    categoryId: item.categoryId,
    mapsPlaceId: null,
    recurrence: { frequency: 'none', count: 1 },
    visibility: 'shared',
  };
}

export function weekendEventToFeedbackItem(item: WeekendEventPick): WeekendResearchItem {
  return {
    id: item.id,
    title: item.title,
    emoji: item.emoji,
    categoryId: item.categoryId,
    dateLabel: item.dateLabel,
    start: item.start,
    end: item.end,
    area: item.area,
    locationName: item.locationName,
    nearestStation: item.nearestStation,
    price: item.price,
    reservation: item.reservation,
    rainFriendly: item.rainFriendly ?? item.tags.includes('屋内'),
    tags: item.tags,
    summary: item.summary,
    coupleNote: item.coupleNote ?? item.summary,
    sourceName: item.sourceName,
    url: item.url,
    imageUrl: item.imageUrl ?? null,
  };
}

export function weekendEventToInitialWithResearch(item: WeekendEventPick): Partial<EventFormValue> {
  return weekendEventToInitial(item);
}

export function weekendEventToFeedbackItemWithResearch(item: WeekendEventPick): WeekendResearchItem {
  return weekendEventToFeedbackItem(item);
}
